### ISSUE TITLE
please explain about what are the pre_actions in wgail_info.py file.

### ISSUE THREAD

**Issue by shamanez** [YunzhuLi/InfoGAIL#13]
There is a pre_action.npz file in the human0 dataset and inside that there is a file with 200 rows and 3 columns. please explain what is that.

**Comment by YunzhuLi** [comment]
It's a prerecorded 200 time-step action (steering, acceleration, brake) that aims to guide the agent leaving from the track's starting point to the place where we want to deploy the learned model.
