### ISSUE TITLE
SetFromFlat function doesn't work

### ISSUE THREAD

**Issue by MarvineGothic** [YunzhuLi/InfoGAIL#17]
I'm sure there is a bug in set_from_flat function, where shapes must be a list:
```
shapes = list(map(var_shape, var_list))
```
instead of a map
```
shapes = map(var_shape, var_list)
```
Therefore it does not iterate: 
```
        for (shape, v) in zip(shapes, var_list):
            size = np.prod(shape)
            assigns.append(tf.assign(v, tf.reshape(theta[start:start + size], shape)))
            start += size
```
As this function was not working the generator policy was not updating neither, because it didn't set `xnew` (which called "new theta") to discriminator. Therefore `fval` was equal to `newfval` which are surrogate losses (it's amazing why all variable should be named so wrong, really hard to read and understand the code!). It gives `actual_improve` and `ratio` == 0. 

```
def linesearch(f, x, fullstep, expected_improve_rate):
    accept_ratio = .1
    max_backtracks = 10
    fval = f(x)
    for (_n_backtracks, stepfrac) in enumerate(.5 ** np.arange(max_backtracks)):
        xnew = x + stepfrac * fullstep
        newfval = f(xnew)
        actual_improve = fval - newfval
        expected_improve = expected_improve_rate * stepfrac
        ratio = actual_improve / expected_improve
        if ratio > accept_ratio and actual_improve > 0:
            return xnew
    return x
```

You can try to run simple test:
```
from keras.initializers import VarianceScaling
from keras.layers import Conv2D

from wgail_info_0.utils import *


def create_generator(feats_tensor, auxs_tensor, encodes_tensor):
    feats = Input(tensor=feats_tensor)
    x = Conv2D(256, (3, 3))(feats)
    x = LeakyReLU()(x)
    x = Conv2D(256, (3, 3), strides=(2, 2))(x)
    x = LeakyReLU()(x)
    x = Flatten()(x)
    auxs = Input(tensor=auxs_tensor)
    h = merge.concatenate([x, auxs])
    h = Dense(256)(h)
    h = LeakyReLU()(h)
    h = Dense(128)(h)
    encodes = Input(tensor=encodes_tensor)
    c = Dense(128)(encodes)
    h = merge.add([h, c])
    h = LeakyReLU()(h)

    steer = Dense(1, activation='tanh', kernel_initializer=lambda shape: VarianceScaling(scale=1e-4)(shape))(h)
    accel = Dense(1, activation='sigmoid', kernel_initializer=lambda shape: VarianceScaling(scale=1e-4)(shape))(h)
    brake = Dense(1, activation='sigmoid', kernel_initializer=lambda shape: VarianceScaling(scale=1e-4)(shape))(h)
    actions = merge.concatenate([steer, accel, brake])
    return Model(inputs=[feats, auxs, encodes], outputs=actions)


if __name__ == '__main__':
    np.random.seed(1024)

    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    sess = tf.Session(config=config)
    from keras import backend as K

    K.set_session(sess)

    feat_dim = [7, 13, 1024]
    img_dim = [50, 50, 3]
    aux_dim = 10
    encode_dim = 2
    action_dim = 3

    feats = tf.placeholder(dtype, shape=[None, feat_dim[0], feat_dim[1], feat_dim[2]], name="feats")
    auxs = tf.placeholder(dtype, shape=[None, aux_dim], name="auxs")
    encodes = tf.placeholder(dtype, shape=[None, encode_dim], name="encodes")

    pi = create_generator(feats, auxs, encodes)
    var_list = pi.trainable_weights
    get_flat = GetFlat(sess, var_list)
    set_from_flat = SetFromFlat(sess, var_list)

    sess.run(tf.global_variables_initializer())

    th_prev = get_flat()
    th_new = th_prev * 2
    print("th_prev equals th_new:", np.array_equal(th_prev, th_new))

    print("Set th_new")
    set_from_flat(th_new)
    th_after = get_flat()

    print("Didn't update" if np.array_equal(th_prev, th_after) else "Updated")

    print("th_new equals th_after:", np.array_equal(th_new, th_after))

```

**Comment by YunzhuLi** [comment]
Hi Sergiy,

Thank you for pointing this out. Would you please let me know the versions of your Python, Tensorflow, and Keras? Specifically, are you using Python 3? The code was working fine using Python 2.7, Tensorflow 0.12.1and Keras 1.2.2, as I've stated in the readme.

To give you more context, I brought the implementation of TRPO from this [repo](https://github.com/wojzaremba/trpo), where the functions of `SetFromFlat` and `linesearch` are exactly the same, please see [here](https://github.com/wojzaremba/trpo/blob/06cef3ea78b240620136900cca4ab7b963ab90d1/utils.py#L123) and [here](https://github.com/wojzaremba/trpo/blob/06cef3ea78b240620136900cca4ab7b963ab90d1/utils.py#L169).

If you have concerns with naming in the function `linesearch`, you can also refer to these implementations, [here](https://github.com/ikostrikov/pytorch-trpo/blob/e200eb8a23b3c7941a0091efb9750dafa4b23cbb/trpo.py#L27), [here](https://github.com/joschu/modular_rl/blob/6970cde3da265cf2a98537250fea5e0c0d9a7639/modular_rl/trpo.py#L104), and [here](https://github.com/MahanFathi/TRPO-TensorFlow/blob/de8f20efcb97f327d982fdf2718cff08091dd7ce/trpo.py#L110), where people are adopting the same naming practice.

Best,
Yunzhu

**Comment by MarvineGothic** [comment]
Yes, I'm using Python 3. I can't use Python 2.7 because it's too old for other projects, so I didn't try it. So I think you are right about that, and it's not a bug but just a different Python version. Sorry for inconvenience! But anyways, I hope it will help other programmers who want to shift to Python 3. 
And I understand that you utilized some other codes, but still you could change names to something more meaningful. It's not a requirement but rather a good suggestion, so for us it would be much easier to understand the code and all that math behind it.
However, apart from the this, I just want to apologize and leave a good feedback on this project. It's a great job you've done!
