### ISSUE TITLE
Can I run your code on GPU

### ISSUE THREAD

**Issue by makotovnjp** [YunzhuLi/InfoGAIL#18]
Dear 

I have tried to run your code on GPU by these steps.
1. Make conda virtual enviroment with packages in README.md
2. pip install tensorflow-gpu on the above conda virtual enviroment
3. run python wgail_info.py

But there are some errors like 

Traceback (most recent call last):
  File "wgail_info.py", line 12, in <module>
    from models import TRPOAgent
  File "/home/dl-box/InfoGAIL_Survey/original_InfoGAIL/wgail_info_0/models.py", line 1, in <module>
    from utils import *
  File "/home/dl-box/InfoGAIL_Survey/original_InfoGAIL/wgail_info_0/utils.py", line 22, in <module>
    tf.set_random_seed(seed)
AttributeError: 'module' object has no attribute 'set_random_seed'

I suppose that the version tensorflow-gpu doesn't match with your code.
If you have run your code on GPU, Please tell me tensorflow-gpu's version or give me some guides to run on GPU.

Thank you very much.

**Comment by YunzhuLi** [comment]
I was running my code on GPU using Tensorflow 0.12.1, as indicated in the readme. Is it the same version as you are using?

**Comment by makotovnjp** [comment]
@YunzhuLi 
Hi Yunzhuli.

Thanks for your advice. I've installed GPU Tensorflow 0.12.1 and cudatoolkit==8.0. After that, I can run on the GPU but the same error with #9  occurred.

Hope your helps

**Comment by makotovnjp** [comment]
After installing cudnn 5.1, now I can your code on GPU.
conda install -c anaconda cudnn==5.1

Thank you.
