### ISSUE TITLE
What is the meaning of logstd in the code?

### ISSUE THREAD

**Issue by jingxingdaze** [YunzhuLi/InfoGAIL#21]
What is the meaning of logstd in the code? And how to initialize the value for it? Why did you assignment it as [-2.8, -3.5] or [-3.5, -4].

**Comment by YunzhuLi** [comment]
As the name suggests, `logstd` is the logarithm of the action's standard deviation, which controls the agent's action distribution. The value is initialized for the agent to have reasonable initial explorative behaviors.

**Comment by jingxingdaze** [comment]
> 

Understand, thank you.
